name: CI

on:
  push:
    branches: [ main, master, feature-improved-ui ]
  pull_request:
    branches: [ main, master ]

jobs:
  frontend:
    name: Frontend - install, build & test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install frontend deps
        working-directory: ./frontend
        run: npm ci

      - name: Run frontend lint
        working-directory: ./frontend
        run: |
          if [ -f package.json ]; then
            npm run lint --if-present || true
          fi

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build --if-present

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test --if-present -- --watchAll=false

  backend:
    name: Backend - install, build & test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install backend deps
        working-directory: ./backend
        run: npm ci

      - name: Run backend lint
        working-directory: ./backend
        run: |
          if [ -f package.json ]; then
            npm run lint --if-present || true
          fi

      - name: Run backend tests
        working-directory: ./backend
        run: npm test --if-present -- --runInBand || true

  combined-checks:
    name: Combined quick checks
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print summary
        run: echo "Frontend and Backend jobs completed"
